; https://worldofspectrum.org/faq/reference/48kreference.htm#PortFE
ZX_PORT_ULA           equ $FE    ; MIC, EAR and border
ZX_PORT_KEYB_L4       equ $FEFE   ; Keyboard bottom row lhs - SHIFT, Z, X, C, V
ZX_PORT_KEYB_L3       equ $FDFE   ; Keyboard - A, S, D, F, G
ZX_PORT_KEYB_L2       equ $FBFE   ; Keyboard - Q, W, E, R, T
ZX_PORT_KEYB_L1       equ $F7FE   ; Keyboard top row lhs - 1, 2, 3, 4, 5
ZX_PORT_KEYB_R1       equ $EFFE   ; Keyboard top row rhs - 0, 9, 8, 7, 6
ZX_PORT_KEYB_R2       equ $DFFE   ; Keyboard - P, O, I, U, Y
ZX_PORT_KEYB_R3       equ $BFFE   ; Keyboard - ENTER, L, K, J, H
ZX_PORT_KEYB_R4       equ $7FFE   ; Keyboard bottom row rhs - SPACE, SYM SHFT, M, N, B